### ISSUE TITLE
Error trying to use in Next.JS

### ISSUE THREAD

**Issue by jonrrivera** [eckdev/react-horizontal-scroll#8]
Hi, 

I just installed this module in my next js app and I am getting the error. Can you please advise.

<img width="973" alt="Screen Shot 2020-08-17 at 8 46 46 PM" src="https://user-images.githubusercontent.com/18686388/90468209-0f2d1700-e0e4-11ea-986b-66e9c909890f.png">

**Comment by eckdev** [comment]
hello mate, seem like a, you can not install the 'react-basic-horizontal-scroll'. Can you try again ?
